export const SURAH = [
  {
    number: 1,
    name: "سُورَةُ ٱلْفَاتِحَةِ",
    englishName: "Al-Faatiha",
    englishNameTranslation: "The Opening",
    revelationType: "Meccan",
    ayahsNumbers: 7,
  },
  {
    number: 2,
    name: "سُورَةُ البَقَرَةِ",
    englishName: "Al-Baqara",
    englishNameTranslation: "The Cow",
    revelationType: "Medinan",
    ayahsNumbers: 286,
  },
  {
    number: 3,
    name: "سُورَةُ آلِ عِمْرَانَ",
    englishName: "Aal-i-Imraan",
    englishNameTranslation: "The Family of Imraan",
    revelationType: "Medinan",
    ayahsNumbers: 200,
  },
  {
    number: 4,
    name: "سُورَةُ النِّسَاءِ",
    englishName: "An-Nisaa",
    englishNameTranslation: "The Women",
    revelationType: "Medinan",
    ayahsNumbers: 176,
  },
  {
    number: 5,
    name: "سُورَةُ المَائِدَةِ",
    englishName: "Al-Maaida",
    englishNameTranslation: "The Table",
    revelationType: "Medinan",
    ayahsNumbers: 120,
  },
  {
    number: 6,
    name: "سُورَةُ الأَنعَامِ",
    englishName: "Al-An'aam",
    englishNameTranslation: "The Cattle",
    revelationType: "Meccan",
    ayahsNumbers: 165,
  },
  {
    number: 7,
    name: "سُورَةُ الأَعْرَافِ",
    englishName: "Al-A'raaf",
    englishNameTranslation: "The Heights",
    revelationType: "Meccan",
    ayahsNumbers: 206,
  },
  {
    number: 8,
    name: "سُورَةُ الأَنفَالِ",
    englishName: "Al-Anfaal",
    englishNameTranslation: "The Spoils of War",
    revelationType: "Medinan",
    ayahsNumbers: 75,
  },
  {
    number: 9,
    name: "سُورَةُ التَّوْبَةِ",
    englishName: "At-Tawba",
    englishNameTranslation: "The Repentance",
    revelationType: "Medinan",
    ayahsNumbers: 129,
  },
  {
    number: 10,
    name: "سُورَةُ يُونُسَ",
    englishName: "Yunus",
    englishNameTranslation: "Jonas",
    revelationType: "Meccan",
    ayahsNumbers: 109,
  },
  {
    number: 11,
    name: "سُورَةُ هُودٍ",
    englishName: "Hud",
    englishNameTranslation: "Hud",
    revelationType: "Meccan",
    ayahsNumbers: 123,
  },
  {
    number: 12,
    name: "سُورَةُ يُوسُفَ",
    englishName: "Yusuf",
    englishNameTranslation: "Joseph",
    revelationType: "Meccan",
    ayahsNumbers: 111,
  },
  {
    number: 13,
    name: "سُورَةُ الرَّعْدِ",
    englishName: "Ar-Ra'd",
    englishNameTranslation: "The Thunder",
    revelationType: "Medinan",
    ayahsNumbers: 43,
  },
  {
    number: 14,
    name: "سُورَةُ إِبْرَاهِيمَ",
    englishName: "Ibrahim",
    englishNameTranslation: "Abraham",
    revelationType: "Meccan",
    ayahsNumbers: 52,
  },
  {
    number: 15,
    name: "سُورَةُ الحِجْرِ",
    englishName: "Al-Hijr",
    englishNameTranslation: "The Rock",
    revelationType: "Meccan",
    ayahsNumbers: 99,
  },
  {
    number: 16,
    name: "سُورَةُ النَّحْلِ",
    englishName: "An-Nahl",
    englishNameTranslation: "The Bee",
    revelationType: "Meccan",
    ayahsNumbers: 128,
  },
  {
    number: 17,
    name: "سُورَةُ الإِسْرَاءِ",
    englishName: "Al-Israa",
    englishNameTranslation: "The Night Journey",
    revelationType: "Meccan",
    ayahsNumbers: 111,
  },
  {
    number: 18,
    name: "سُورَةُ الكَهْفِ",
    englishName: "Al-Kahf",
    englishNameTranslation: "The Cave",
    revelationType: "Meccan",
    ayahsNumbers: 110,
  },
  {
    number: 19,
    name: "سُورَةُ مَرْيَمَ",
    englishName: "Maryam",
    englishNameTranslation: "Mary",
    revelationType: "Meccan",
    ayahsNumbers: 98,
  },
  {
    number: 20,
    name: "سُورَةُ طه",
    englishName: "Taa-Haa",
    englishNameTranslation: "Taa-Haa",
    revelationType: "Meccan",
    ayahsNumbers: 135,
  },
  {
    number: 21,
    name: "سُورَةُ الأَنْبِيَاءِ",
    englishName: "Al-Anbiyaa",
    englishNameTranslation: "The Prophets",
    revelationType: "Meccan",
    ayahsNumbers: 112,
  },
  {
    number: 22,
    name: "سُورَةُ الحَجِّ",
    englishName: "Al-Hajj",
    englishNameTranslation: "The Pilgrimage",
    revelationType: "Medinan",
    ayahsNumbers: 78,
  },
  {
    number: 23,
    name: "سُورَةُ المُؤْمِنُونَ",
    englishName: "Al-Muminun",
    englishNameTranslation: "The Believers",
    revelationType: "Meccan",
    ayahsNumbers: 118,
  },
  {
    number: 24,
    name: "سُورَةُ النُّورِ",
    englishName: "An-Noor",
    englishNameTranslation: "The Light",
    revelationType: "Medinan",
    ayahsNumbers: 64,
  },
  {
    number: 25,
    name: "سُورَةُ الفُرْقَانِ",
    englishName: "Al-Furqaan",
    englishNameTranslation: "The Criterion",
    revelationType: "Meccan",
    ayahsNumbers: 77,
  },
  {
    number: 26,
    name: "سُورَةُ الشُّعَرَاءِ",
    englishName: "Ash-Shu'araa",
    englishNameTranslation: "The Poets",
    revelationType: "Meccan",
    ayahsNumbers: 227,
  },
  {
    number: 27,
    name: "سُورَةُ النَّمْلِ",
    englishName: "An-Naml",
    englishNameTranslation: "The Ant",
    revelationType: "Meccan",
    ayahsNumbers: 93,
  },
  {
    number: 28,
    name: "سُورَةُ القَصَصِ",
    englishName: "Al-Qasas",
    englishNameTranslation: "The Stories",
    revelationType: "Meccan",
    ayahsNumbers: 88,
  },
  {
    number: 29,
    name: "سُورَةُ العَنْكَبُوتِ",
    englishName: "Al-Ankabut",
    englishNameTranslation: "The Spider",
    revelationType: "Meccan",
    ayahsNumbers: 69,
  },
  {
    number: 30,
    name: "سُورَةُ الرُّومِ",
    englishName: "Ar-Room",
    englishNameTranslation: "The Romans",
    revelationType: "Meccan",
    ayahsNumbers: 60,
  },
  {
    number: 31,
    name: "سُورَةُ لُقْمَانَ",
    englishName: "Luqman",
    englishNameTranslation: "Luqman",
    revelationType: "Meccan",
    ayahsNumbers: 34,
  },
  {
    number: 32,
    name: "سُورَةُ السَّجْدَةِ",
    englishName: "As-Sajda",
    englishNameTranslation: "The Prostration",
    revelationType: "Meccan",
    ayahsNumbers: 30,
  },
  {
    number: 33,
    name: "سُورَةُ الأَحْزَابِ",
    englishName: "Al-Ahzaab",
    englishNameTranslation: "The Clans",
    revelationType: "Medinan",
    ayahsNumbers: 73,
  },
  {
    number: 34,
    name: "سُورَةُ سَبَإٍ",
    englishName: "Saba",
    englishNameTranslation: "Sheba",
    revelationType: "Meccan",
    ayahsNumbers: 54,
  },
  {
    number: 35,
    name: "سُورَةُ فَاطِرٍ",
    englishName: "Faatir",
    englishNameTranslation: "The Originator",
    revelationType: "Meccan",
    ayahsNumbers: 45,
  },
  {
    number: 36,
    name: "سُورَةُ يس",
    englishName: "Yaseen",
    englishNameTranslation: "Yaseen",
    revelationType: "Meccan",
    ayahsNumbers: 83,
  },
  {
    number: 37,
    name: "سُورَةُ الصَّافَّاتِ",
    englishName: "As-Saaffaat",
    englishNameTranslation: "Those Who Set The Ranks",
    revelationType: "Meccan",
    ayahsNumbers: 182,
  },
  {
    number: 38,
    name: "سُورَةُ ص",
    englishName: "Saad",
    englishNameTranslation: "The letter Saad",
    revelationType: "Meccan",
    ayahsNumbers: 88,
  },
  {
    number: 39,
    name: "سُورَةُ الزُّمَرِ",
    englishName: "Az-Zumar",
    englishNameTranslation: "The Troops",
    revelationType: "Meccan",
    ayahsNumbers: 75,
  },
  {
    number: 40,
    name: "سُورَةُ غَافِرٍ",
    englishName: "Ghafir",
    englishNameTranslation: "The Forgiver",
    revelationType: "Meccan",
    ayahsNumbers: 85,
  },
  {
    number: 41,
    name: "سُورَةُ فُصِّلَتْ",
    englishName: "Fussilat",
    englishNameTranslation: "Explained in detail",
    revelationType: "Meccan",
    ayahsNumbers: 54,
  },
  {
    number: 42,
    name: "سُورَةُ الشُّورَىٰ",
    englishName: "Ash-Shura",
    englishNameTranslation: "The Consultation",
    revelationType: "Meccan",
    ayahsNumbers: 53,
  },
  {
    number: 43,
    name: "سُورَةُ الزُّخْرُفِ",
    englishName: "Az-Zukhruf",
    englishNameTranslation: "The Gold Adornments",
    revelationType: "Meccan",
    ayahsNumbers: 89,
  },
  {
    number: 44,
    name: "سُورَةُ الدُّخَانِ",
    englishName: "Ad-Dukhan",
    englishNameTranslation: "The Smoke",
    revelationType: "Meccan",
    ayahsNumbers: 59,
  },
  {
    number: 45,
    name: "سُورَةُ الجَاثِيَةِ",
    englishName: "Al-Jaathiya",
    englishNameTranslation: "The Kneeling",
    revelationType: "Meccan",
    ayahsNumbers: 37,
  },
  {
    number: 46,
    name: "سُورَةُ الأَحْقَافِ",
    englishName: "Al-Ahqaaf",
    englishNameTranslation: "The Wind-Curved Sandhills",
    revelationType: "Meccan",
    ayahsNumbers: 35,
  },
  {
    number: 47,
    name: "سُورَةُ مُحَمَّدٍ",
    englishName: "Muhammad",
    englishNameTranslation: "Muhammad",
    revelationType: "Medinan",
    ayahsNumbers: 38,
  },
  {
    number: 48,
    name: "سُورَةُ الفَتْحِ",
    englishName: "Al-Fath",
    englishNameTranslation: "The Victory",
    revelationType: "Medinan",
    ayahsNumbers: 29,
  },
  {
    number: 49,
    name: "سُورَةُ الحُجُرَاتِ",
    englishName: "Al-Hujuraat",
    englishNameTranslation: "The Private Apartments",
    revelationType: "Medinan",
    ayahsNumbers: 18,
  },
  {
    number: 50,
    name: "سُورَةُ ق",
    englishName: "Qaaf",
    englishNameTranslation: "The letter Qaaf",
    revelationType: "Meccan",
    ayahsNumbers: 45,
  },
  {
    number: 51,
    name: "سُورَةُ الذَّارِيَاتِ",
    englishName: "Adh-Dhaariyat",
    englishNameTranslation: "The Winnowing Winds",
    revelationType: "Meccan",
    ayahsNumbers: 60,
  },
  {
    number: 52,
    name: "سُورَةُ الطُّورِ",
    englishName: "At-Tur",
    englishNameTranslation: "The Mount",
    revelationType: "Meccan",
    ayahsNumbers: 49,
  },
  {
    number: 53,
    name: "سُورَةُ النَّجْمِ",
    englishName: "An-Najm",
    englishNameTranslation: "The Star",
    revelationType: "Meccan",
    ayahsNumbers: 62,
  },
  {
    number: 54,
    name: "سُورَةُ القَمَرِ",
    englishName: "Al-Qamar",
    englishNameTranslation: "The Moon",
    revelationType: "Meccan",
    ayahsNumbers: 55,
  },
  {
    number: 55,
    name: "سُورَةُ الرَّحْمَٰن",
    englishName: "Ar-Rahmaan",
    englishNameTranslation: "The Most Merciful",
    revelationType: "Medinan",
    ayahsNumbers: 78,
  },
  {
    number: 56,
    name: "سُورَةُ الوَاقِعَةِ",
    englishName: "Al-Waaqi'a",
    englishNameTranslation: "The Event",
    revelationType: "Meccan",
    ayahsNumbers: 96,
  },
  {
    number: 57,
    name: "سُورَةُ الحَدِيدِ",
    englishName: "Al-Hadid",
    englishNameTranslation: "The Iron",
    revelationType: "Medinan",
    ayahsNumbers: 29,
  },
  {
    number: 58,
    name: "سُورَةُ المُجَادِلَةِ",
    englishName: "Al-Mujaadila",
    englishNameTranslation: "The Pleading Woman",
    revelationType: "Medinan",
    ayahsNumbers: 22,
  },
  {
    number: 59,
    name: "سُورَةُ الحَشْرِ",
    englishName: "Al-Hashr",
    englishNameTranslation: "The Exile",
    revelationType: "Medinan",
    ayahsNumbers: 24,
  },
  {
    number: 60,
    name: "سُورَةُ المُمْتَحَنَةِ",
    englishName: "Al-Mumtahana",
    englishNameTranslation: "She That Is To Be Examined",
    revelationType: "Medinan",
    ayahsNumbers: 13,
  },
  {
    number: 61,
    name: "سُورَةُ الصَّفِّ",
    englishName: "As-Saff",
    englishNameTranslation: "The Ranks",
    revelationType: "Medinan",
    ayahsNumbers: 14,
  },
  {
    number: 62,
    name: "سُورَةُ الجُمُعَةِ",
    englishName: "Al-Jumu'a",
    englishNameTranslation: "The Congregation, Friday",
    revelationType: "Medinan",
    ayahsNumbers: 11,
  },
  {
    number: 63,
    name: "سُورَةُ المُنَافِقُونَ",
    englishName: "Al-Munaafiqoon",
    englishNameTranslation: "The Hypocrites",
    revelationType: "Medinan",
    ayahsNumbers: 11,
  },
  {
    number: 64,
    name: "سُورَةُ التَّغَابُنِ",
    englishName: "At-Taghaabun",
    englishNameTranslation: "Mutual Disillusion",
    revelationType: "Medinan",
    ayahsNumbers: 18,
  },
  {
    number: 65,
    name: "سُورَةُ الطَّلَاقِ",
    englishName: "At-Talaaq",
    englishNameTranslation: "The Divorce",
    revelationType: "Medinan",
    ayahsNumbers: 12,
  },
  {
    number: 66,
    name: "سُورَةُ التَّحْرِيمِ",
    englishName: "At-Tahrim",
    englishNameTranslation: "The Prohibition",
    revelationType: "Medinan",
    ayahsNumbers: 12,
  },
  {
    number: 67,
    name: "سُورَةُ المُلْكِ",
    englishName: "Al-Mulk",
    englishNameTranslation: "The Sovereignty",
    revelationType: "Meccan",
    ayahsNumbers: 30,
  },
  {
    number: 68,
    name: "سُورَةُ القَلَمِ",
    englishName: "Al-Qalam",
    englishNameTranslation: "The Pen",
    revelationType: "Meccan",
    ayahsNumbers: 52,
  },
  {
    number: 69,
    name: "سُورَةُ الحَاقَّةِ",
    englishName: "Al-Haaqqa",
    englishNameTranslation: "The Reality",
    revelationType: "Meccan",
    ayahsNumbers: 52,
  },
  {
    number: 70,
    name: "سُورَةُ المَعَارِجِ",
    englishName: "Al-Ma'arij",
    englishNameTranslation: "The Ascending Stairways",
    revelationType: "Meccan",
    ayahsNumbers: 44,
  },
  {
    number: 71,
    name: "سُورَةُ نُوحٍ",
    englishName: "Nooh",
    englishNameTranslation: "Noah",
    revelationType: "Meccan",
    ayahsNumbers: 28,
  },
  {
    number: 72,
    name: "سُورَةُ الجِنِّ",
    englishName: "Al-Jinn",
    englishNameTranslation: "The Jinn",
    revelationType: "Meccan",
    ayahsNumbers: 28,
  },
  {
    number: 73,
    name: "سُورَةُ المُزَّمِّلِ",
    englishName: "Al-Muzzammil",
    englishNameTranslation: "The Enshrouded One",
    revelationType: "Meccan",
    ayahsNumbers: 20,
  },
  {
    number: 74,
    name: "سُورَةُ المُدَّثِّرِ",
    englishName: "Al-Muddaththir",
    englishNameTranslation: "The Cloaked One",
    revelationType: "Meccan",
    ayahsNumbers: 56,
  },
  {
    number: 75,
    name: "سُورَةُ القِيَامَةِ",
    englishName: "Al-Qiyaama",
    englishNameTranslation: "The Resurrection",
    revelationType: "Meccan",
    ayahsNumbers: 40,
  },
  {
    number: 76,
    name: "سُورَةُ الإِنسَانِ",
    englishName: "Al-Insaan",
    englishNameTranslation: "The Man",
    revelationType: "Medinan",
    ayahsNumbers: 31,
  },
  {
    number: 77,
    name: "سُورَةُ المُرْسَلَاتِ",
    englishName: "Al-Mursalaat",
    englishNameTranslation: "The Emissaries",
    revelationType: "Meccan",
    ayahsNumbers: 50,
  },
  {
    number: 78,
    name: "سُورَةُ النَّبَإِ",
    englishName: "An-Naba",
    englishNameTranslation: "The Tidings",
    revelationType: "Meccan",
    ayahsNumbers: 40,
  },
  {
    number: 79,
    name: "سُورَةُ النَّازِعَاتِ",
    englishName: "An-Naazi'aat",
    englishNameTranslation: "Those Who Pull Out",
    revelationType: "Meccan",
    ayahsNumbers: 46,
  },
  {
    number: 80,
    name: "سُورَةُ عَبَسَ",
    englishName: "'Abasa",
    englishNameTranslation: "He Frowned",
    revelationType: "Meccan",
    ayahsNumbers: 42,
  },
  {
    number: 81,
    name: "سُورَةُ التَّكْوِيرِ",
    englishName: "At-Takwir",
    englishNameTranslation: "The Overthrowing",
    revelationType: "Meccan",
    ayahsNumbers: 29,
  },
  {
    number: 82,
    name: "سُورَةُ الانفِطَارِ",
    englishName: "Al-Infitaar",
    englishNameTranslation: "The Cleaving",
    revelationType: "Meccan",
    ayahsNumbers: 19,
  },
  {
    number: 83,
    name: "سُورَةُ المُطَفِّفِينَ",
    englishName: "Al-Mutaffifin",
    englishNameTranslation: "The Defrauding",
    revelationType: "Meccan",
    ayahsNumbers: 36,
  },
  {
    number: 84,
    name: "سُورَةُ الانشِقَاقِ",
    englishName: "Al-Inshiqaaq",
    englishNameTranslation: "The Sundering",
    revelationType: "Meccan",
    ayahsNumbers: 25,
  },
  {
    number: 85,
    name: "سُورَةُ البُرُوجِ",
    englishName: "Al-Burooj",
    englishNameTranslation: "The Mansions of the Stars",
    revelationType: "Meccan",
    ayahsNumbers: 22,
  },
  {
    number: 86,
    name: "سُورَةُ الطَّارِقِ",
    englishName: "At-Taariq",
    englishNameTranslation: "The Nightcommer",
    revelationType: "Meccan",
    ayahsNumbers: 17,
  },
  {
    number: 87,
    name: "سُورَةُ الأَعْلَىٰ",
    englishName: "Al-A'laa",
    englishNameTranslation: "The Most High",
    revelationType: "Meccan",
    ayahsNumbers: 19,
  },
  {
    number: 88,
    name: "سُورَةُ الغَاشِيَةِ",
    englishName: "Al-Ghaashiya",
    englishNameTranslation: "The Overwhelming",
    revelationType: "Meccan",
    ayahsNumbers: 26,
  },
  {
    number: 89,
    name: "سُورَةُ الفَجْرِ",
    englishName: "Al-Fajr",
    englishNameTranslation: "The Dawn",
    revelationType: "Meccan",
    ayahsNumbers: 30,
  },
  {
    number: 90,
    name: "سُورَةُ البَلَدِ",
    englishName: "Al-Balad",
    englishNameTranslation: "The City",
    revelationType: "Meccan",
    ayahsNumbers: 20,
  },
  {
    number: 91,
    name: "سُورَةُ الشَّمْسِ",
    englishName: "Ash-Shams",
    englishNameTranslation: "The Sun",
    revelationType: "Meccan",
    ayahsNumbers: 15,
  },
  {
    number: 92,
    name: "سُورَةُ اللَّيْلِ",
    englishName: "Al-Layl",
    englishNameTranslation: "The Night",
    revelationType: "Meccan",
    ayahsNumbers: 21,
  },
  {
    number: 93,
    name: "سُورَةُ الضُّحَىٰ",
    englishName: "Ad-Duhaa",
    englishNameTranslation: "The Morning Hours",
    revelationType: "Meccan",
    ayahsNumbers: 11,
  },
  {
    number: 94,
    name: "سُورَةُ الشَّرْحِ",
    englishName: "Ash-Sharh",
    englishNameTranslation: "The Consolation",
    revelationType: "Meccan",
    ayahsNumbers: 8,
  },
  {
    number: 95,
    name: "سُورَةُ التِّينِ",
    englishName: "At-Tin",
    englishNameTranslation: "The Fig",
    revelationType: "Meccan",
    ayahsNumbers: 8,
  },
  {
    number: 96,
    name: "سُورَةُ العَلَقِ",
    englishName: "Al-'Alaq",
    englishNameTranslation: "The Clot",
    revelationType: "Meccan",
    ayahsNumbers: 19,
  },
  {
    number: 97,
    name: "سُورَةُ القَدْرِ",
    englishName: "Al-Qadr",
    englishNameTranslation: "The Power",
    revelationType: "Meccan",
    ayahsNumbers: 5,
  },
  {
    number: 98,
    name: "سُورَةُ البَيِّنَةِ",
    englishName: "Al-Bayyina",
    englishNameTranslation: "The Clear Proof",
    revelationType: "Medinan",
    ayahsNumbers: 8,
  },
  {
    number: 99,
    name: "سُورَةُ الزَّلْزَلَةِ",
    englishName: "Az-Zalzala",
    englishNameTranslation: "The Earthquake",
    revelationType: "Medinan",
    ayahsNumbers: 8,
  },
  {
    number: 100,
    name: "سُورَةُ العَادِيَاتِ",
    englishName: "Al-'Aadiyaat",
    englishNameTranslation: "The Courser",
    revelationType: "Meccan",
    ayahsNumbers: 11,
  },
  {
    number: 101,
    name: "سُورَةُ القَارِعَةِ",
    englishName: "Al-Qaari'a",
    englishNameTranslation: "The Calamity",
    revelationType: "Meccan",
    ayahsNumbers: 11,
  },
  {
    number: 102,
    name: "سُورَةُ التَّكَاثُرِ",
    englishName: "At-Takaathur",
    englishNameTranslation: "The Rivalry in World Increase",
    revelationType: "Meccan",
    ayahsNumbers: 8,
  },
  {
    number: 103,
    name: "سُورَةُ العَصْرِ",
    englishName: "Al-'Asr",
    englishNameTranslation: "The Declining Day, The Epoch",
    revelationType: "Meccan",
    ayahsNumbers: 3,
  },
  {
    number: 104,
    name: "سُورَةُ الهُمَزَةِ",
    englishName: "Al-Humaza",
    englishNameTranslation: "The Traducer",
    revelationType: "Meccan",
    ayahsNumbers: 9,
  },
  {
    number: 105,
    name: "سُورَةُ الفِيلِ",
    englishName: "Al-Fil",
    englishNameTranslation: "The Elephant",
    revelationType: "Meccan",
    ayahsNumbers: 5,
  },
  {
    number: 106,
    name: "سُورَةُ قُرَيْشٍ",
    englishName: "Quraish",
    englishNameTranslation: "Quraish",
    revelationType: "Meccan",
    ayahsNumbers: 4,
  },
  {
    number: 107,
    name: "سُورَةُ المَاعُونِ",
    englishName: "Al-Maa'un",
    englishNameTranslation: "The Small Kindnesses",
    revelationType: "Meccan",
    ayahsNumbers: 7,
  },
  {
    number: 108,
    name: "سُورَةُ الكَوْثَرِ",
    englishName: "Al-Kawthar",
    englishNameTranslation: "The Abundance",
    revelationType: "Meccan",
    ayahsNumbers: 3,
  },
  {
    number: 109,
    name: "سُورَةُ الكَافِرُونَ",
    englishName: "Al-Kaafiroon",
    englishNameTranslation: "The Disbelievers",
    revelationType: "Meccan",
    ayahsNumbers: 6,
  },
  {
    number: 110,
    name: "سُورَةُ النَّصْرِ",
    englishName: "An-Nasr",
    englishNameTranslation: "The Divine Support",
    revelationType: "Medinan",
    ayahsNumbers: 3,
  },
  {
    number: 111,
    name: "سُورَةُ المَسَدِ",
    englishName: "Al-Masad",
    englishNameTranslation: "The Palm Fibre",
    revelationType: "Meccan",
    ayahsNumbers: 5,
  },
  {
    number: 112,
    name: "سُورَةُ الإِخْلَاصِ",
    englishName: "Al-Ikhlaas",
    englishNameTranslation: "The Sincerity",
    revelationType: "Meccan",
    ayahsNumbers: 4,
  },
  {
    number: 113,
    name: "سُورَةُ الفَلَقِ",
    englishName: "Al-Falaq",
    englishNameTranslation: "The Daybreak",
    revelationType: "Meccan",
    ayahsNumbers: 5,
  },
  {
    number: 114,
    name: "سُورَةُ النَّاسِ",
    englishName: "An-Naas",
    englishNameTranslation: "Mankind",
    revelationType: "Meccan",
    ayahsNumbers: 6,
  },
];
